#!/bin/bash
set -euo pipefail

# Regenerates the Nginx real_ip include from EdgeOne's live back-to-origin IP list
# (https://api.edgeone.ai/ips). EdgeOne rotates these ranges with 14/7/3/1-day advance
# notice (station letter/SMS/email), so this is meant to be re-run periodically rather
# than hand-maintained as a static list that silently goes stale.
#
# NOTE: as of 2026-07-15 this endpoint carries a deprecation notice — "stopped serving
# 2026-07-31, offline 2026-08-31". Before that date, find the replacement source (check
# https://cloud.tencent.com/document/product/1552/76086 or the EdgeOne console's own
# origin-protection IP page) and update the curl target below.

OUT=/etc/nginx/conf.d/edgeone-real-ip.conf
TMP=$(mktemp)

{
  echo "# Generated by deploy/update-edgeone-real-ip.sh from https://api.edgeone.ai/ips — do not edit by hand."
  echo "# EdgeOne is the only thing allowed to set X-Forwarded-For here; trusting these ranges is what makes"
  echo "# rate limiting (server/src/middleware/rateLimit.ts) and access logs see real visitor IPs instead of"
  echo "# EdgeOne's own edge node IPs."
  curl -sf https://api.edgeone.ai/ips \
    | grep -E '^[0-9a-fA-F.:]+/[0-9]+$' \
    | sed 's/^/set_real_ip_from /; s/$/;/'
  echo "real_ip_header X-Forwarded-For;"
} > "$TMP"

mv "$TMP" "$OUT"
nginx -t
systemctl reload nginx
echo "Updated $OUT with $(grep -c set_real_ip_from "$OUT") ranges."
